### ISSUE TITLE
Update

### ISSUE THREAD

**Issue by philihp** [weswigham/eve-online-sde#3]
Would it be possible to publish an update on from the latest SDE? The latest update should have for blueprint `57516`, the material type `3645` in quantity `1250`.

**Comment by weswigham** [comment]
I get waaay too many github notices and never saw this - looks like `travis-ci.org` fully shut down so the autoupdate cron job is dead; I'll need to migrate to a github action.

**Comment by philihp** [comment]
That would be great if it could :)

**Comment by philihp** [comment]
That would be great if it could, I'd love to use this as an automagic dependency rather than do it myself.

**Comment by weswigham** [comment]
I doubt anyone cares, but I've had this nagging me at the end of my TODO list for years - finally got around to migrating to an action today. Once again, this repo and npm package should auto-update. Probably. After a short 2.5-year gap.
